### ISSUE TITLE
Setup API on Heroku

### ISSUE THREAD

**Issue by onabright** [BuildForSDG/Team-269-Backend#17]
**Action Required**
Configure API on Heroku for frontend testing

**Comment by geneowak** [comment]
@onabright, I need admin access to the repo in order to finish the setup

**Comment by onabright** [comment]
@geneowak try again.

**Comment by geneowak** [comment]
@onabright we are good now, I'll be adding the necessary files to the project and finishing the deployment and making a PR

**Comment by geneowak** [comment]
This has been successfully completed...
The link is below
https://b4sdg-team269.herokuapp.com/
