### ISSUE TITLE
[FEATURE] Database Design

### ISSUE THREAD

**Issue by onabright** [BuildForSDG/Team-269-Backend#2]
**Action Required**
Document the database tables, columns, constraints and table relationships for the application.
Also document the: 
- Models
- Controllers

**Comment by philbertobuchel** [comment]
@brightonapito
Please find attached database details

Philbert Geoffrey Obuchel
PIM
CCNA
ORACLE 11G
DCIT
BIT

**Comment by victor-otim** [comment]
@philbertobuchel where's the attachment?

**Comment by philbertobuchel** [comment]
@brightonapito
@victorotim
Please find attachment below for database design details
Philbert Geoffrey Obuchel
PIM
CCNA
ORACLE 11G
DCIT
BIT

**Comment by victor-otim** [comment]
@philbertobuchel still can't see any attachments.
thanks

**Comment by onabright** [comment]
@philbertobuchel can you share the attachment on the slack channel?

**Comment by onabright** [comment]
Alright, now we have a working document. @geneowak is going to create the scaffolding for the models and controllers.
