### ISSUE TITLE
[FEATURE] Could we setup CI with circle ci / github actions

### ISSUE THREAD

**Issue by geneowak** [BuildForSDG/Team-269-Backend#20]
**Is your feature request related to a problem? Please describe.**
We need a way to make sure that all the tests pass before merging a PR.

**Describe the solution you'd like**
We setup circle ci and set a min number of checks that should pass before merging the PR. Am thinking of the following:

1. Checkout: The code can successfully run i.e setup on a machine
2. Linting: The code contains no lint errors (the linter has already been setup)
3. Tests passing: All the written tests pass.

**Describe alternatives you've considered**
We can also use github actions but I've not used it before and I can easily setup circle-ci. However if someone is very conversant with github actions they could go let us know.

**Additional context**
![checks](https://user-images.githubusercontent.com/13153526/82594513-e1036e00-9bac-11ea-9624-958780eae5a6.png)

**Comment by onabright** [comment]
@geneowak cool let me look into it.
