### ISSUE TITLE
[FEATURE] Define Backend Functionality

### ISSUE THREAD

**Issue by onabright** [BuildForSDG/Team-269-Backend#5]
**Action Required**
Document all the backend functions that will need to be implemented to bring the app to life. This will form the basis for tasks moving forward.

**Comment by philbertobuchel** [comment]
@brightonapito
Do I have to go to GitHub then clone repository and complete the required
action
Thanks

Philbert Geoffrey Obuchel
PIM
CCNA
ORACLE 11G
DCIT
BIT

**Comment by onabright** [comment]
@philbertobuchel this task doesn't necessarily require you to clone anything. Do this in the document that I shared.
